module.exports =
  CLIENT_ID: process.env.GITHUB_CLIENT_ID
  CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET
  BOT_USERNAME: process.env.BOT_USERNAME
  BOT_PASSWORD: process.env.BOT_PASSWORD
  USER_AGENT: process.env.GITHUB_USER_AGENT
